#Differential Gene Expression Analysis (DeSeq2)

# Installing the libraries

library(DESeq2)
library(ggplot2)


# Read the count file generated by the htseq-count

input <- read.csv("raw_counts_2.csv",sep=',',header=T)
head(input)
input$X<- NULL


#Remove last 5 rows

input2 <- input[-seq(nrow(input),nrow(input)-4),]
tail(input2)


#Making the group and assigning the Wild Type condition as the base level

group<-as.factor(c(rep("A549_WT", 2), rep("A549_TGFB", 2)))
group<- relevel(group, ref = "A549_WT")
head(group)
head(input2)
rownames(input2)<- input2$geneID
head(input2)
input2$geneID<- NULL
head(input2)
mycols<-data.frame(row.names = colnames(input2), group)


#Removing the rows having read sum less than 10

keep <- rowSums(input2) >= 10
input2 <- input2[keep,]
nrow(input)


# Using BiomaRt library to assign the gene names to the ensembl ids

list<-c(row.names(input2), quote(""))
ensembl_version = "uswest.ensembl.org"
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl",host=ensembl_version)
extraInfo <- getBM(attributes = c("ensembl_gene_id","gene_biotype","external_gene_name"),
                   filters = "ensembl_gene_id",
                   values = list,
                   mart = ensembl, useCache = FALSE)
nrow(extraInfo)
annotatedcounts <- merge(input, extraInfo, by.x = 0, by.y = "ensembl_gene_id", sort=FALSE)
nrow(annotatedcounts)
head(annotatedcounts)
write.csv(annotatedcounts,"biomart_output_HCT_p53null.csv")
library(dplyr)
final <- distinct(annotatedcounts,external_gene_name, .keep_all= TRUE)
nrow(final)
head(final)
row.names(final)<- final$external_gene_name
head(final)
finalanno<-final[,2:5]
head(finalanno)


# Running the deseq2 

ddsHTSeq<- DESeqDataSetFromMatrix(countData = input2, colData = mycols, design = ~group)
ddsHTSeq
class(ddsHTSeq)
dds<-DESeq(ddsHTSeq)
resul <- results(dds)
head(resul)
summary(resul)
write.csv(resul,"A549_WT_vs_TGFB_deseq2_output.csv")

